# 第 01 回レポート

## 作成者

- 学籍番号: k24132
- 氏名: 町田 渉

## 問 1

utils.py の list_generator_function 関数の引数に str 型の値を指定した．
list_generator_function 関数では引数は count という変数に代入されており，count が使われている 20 行目で問題が発生する．
発生する問題は，「range 関数の引数は整数の int 型である必要がある」のに対して，引数に与えた変数 count に代入されているのは str 型です．
その結果，list_generator_function が TypeError 例外を発生させ，エラー１が表示されます．

## 問 2

<!-- 上記の問 1 の回答を参考にどのような引数が渡され，それらの引数がどのように処理され，エラーが表示されるかを手順を追って説明する． -->

main.py の 30 行目で print_process 関数を「間違った数値と文字列のペア」で呼び出すように修正した．具体的には，(3, "Fizz") のペアを (3, "Buzz") に変更した．
この変更により，utils.py の 14 行目で問題が発生した．
発生した問題は，「3 の倍数のときに "Fizz" を返す」という fizzbuzz のルールに反していることだ．
その結果，print_process 関数が ValueError 例外を発生させ，エラー２が表示される．
